name: recipe_app
description: A Flutter recipe application with internationalization support.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Internationalization dependencies
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  
  # State management and storage
  provider: ^6.1.2
  shared_preferences: ^2.2.3

  # Other dependencies you might have
  cupertino_icons: ^1.0.2
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # Enable localization generation
  generate: true

  # Assets
  assets:
    - assets/images/recipes/
    - assets/usd_xr.json
